// components/SearchBar/index.tsx
'use client'

import type { NextPage } from 'next'
import { useState } from 'react'
import Image from 'next/image'
import { Input } from '@/components/ui/input'

const SearchBar: NextPage = () => {
  const [searchValue, setSearchValue] = useState('')

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      window.location.href = `https://cn.bing.com/search?q=${searchValue}&form=QBRE`
    }
  }

  return (
    <div className="flex flex-row justify-center pt-26">
      <div className="flex w-140 rounded-2xl bg-[#ffffff80] focus-within:bg-white/90 hover:bg-white/90">
        <div className="flex size-13 items-center justify-center">
          <section className="flex size-8 items-center justify-center rounded-lg hover:cursor-pointer hover:bg-white/50">
            <Image src="/icon-bing.png" alt="bing" width={24} height={24} />
          </section>
        </div>
        <Input
          className="h-13 w-114 border-none px-0 shadow-none focus:ring-0 focus-visible:border-transparent focus-visible:ring-0"
          value={searchValue}
          onChange={(e) => setSearchValue(e.target.value)}
          onKeyDown={handleKeyDown}
        />
        <div className="size-13"></div>
      </div>
    </div>
  )
}

export default SearchBar

// src/components/SearchBar.vue
<template>
  <div>
    <div class="search-bar" ref="searchBarRef">
      <section class="search-engine flex-center">
        <section class="icon-box flex-center">
          <img src="/images/icon-bing-48.png" alt="bing" />
        </section>
      </section>
      <Input
        class="search-input"
        placeholder="输入搜索内容"
        v-model:value="searchValue"
        v-on:press-enter="search"
        @focus="handleInputFocus"
        @blur="handleInputBlur"
      />
      <section class="clear-icon-box flex-center">
        <CloseCircleFilled
          v-show="searchValue"
          class="clear-icon"
          @click="clearInput"
        />
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Input } from 'ant-design-vue'
import { CloseCircleFilled } from '@ant-design/icons-vue'

let searchValue = ref<string>('')

function search() {
  window.location.href =
    'https://cn.bing.com/search?q=' + searchValue.value + '&form=QBRE'
}

function clearInput() {
  searchValue.value = ''
}

const searchBarRef = ref<HTMLInputElement | null>(null)
let handleInputFocus = () => {
  searchBarRef.value?.classList.add('search-bar-active')
}
let handleInputBlur = () => {
  searchBarRef.value?.classList.remove('search-bar-active')
}
</script>

<style scoped lang="scss">
.flex-center {
  display: flex;
  align-items: center;
  justify-content: center;
}
.search-bar {
  width: 560px;
  height: 52px;
  background-color: rgb(255, 255, 255, 0.5);
  position: absolute;
  top: 15vh;
  left: 50%;
  transform: translate(-50%, -50%);
  border-radius: 15px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  .search-engine {
    width: 52px;
    height: 52px;
    flex: none;
    .icon-box {
      width: 32px;
      height: 32px;
      border-radius: 8px;
      &:hover {
        background-color: rgb(255, 255, 255, 0.6);
      }
      img {
        width: 24px;
        height: 24px;
        display: block;
      }
    }
  }
  .search-input {
    color: #526071;
    font-size: 16px;
    line-height: 28px;
    font-family:
      ui-sans-serif,
      system-ui,
      -apple-system,
      BlinkMacSystemFont,
      'Segoe UI',
      Roboto,
      'Helvetica Neue',
      Arial,
      sans-serif;
    border: 0;
    outline: none;
    background: rgba(0, 0, 0, 0);
    box-shadow: none;
  }
  .clear-icon-box {
    width: 52px;
    height: 52px;
    flex: none;
    .clear-icon {
      color: rgba(0, 0, 0, 0.4);
    }
  }
}
.search-bar-active {
  background-color: #fff;
  .search-input {
    color: #2d2e2e;
  }
}
</style>
